export const TRADES = [
  "HVAC",
  "Roofing",
  "Plumbing",
  "Electrical",
  "Landscaping",
  "Painting",
  "Solar",
  "General Contractor",
  "Other",
] as const;

export type Trade = (typeof TRADES)[number];

export const TRADE_SERVICES: Record<Trade, string[]> = {
  HVAC: ["AC Repair", "Furnace Install", "Duct Cleaning", "System Tune-Up", "Emergency HVAC", "Free Estimates"],
  Roofing: ["Roof Repair", "Roof Replacement", "Inspections", "Gutter Install", "Leak Repair", "Free Estimates"],
  Plumbing: ["Drain Cleaning", "Pipe Repair", "Water Heater", "Fixture Install", "Emergency Plumbing", "Free Estimates"],
  Electrical: ["Wiring & Rewiring", "Panel Upgrades", "Outlet Install", "Lighting", "Emergency Electrical", "Free Estimates"],
  Landscaping: ["Lawn Care", "Tree Trimming", "Hardscaping", "Irrigation", "Seasonal Cleanup", "Free Estimates"],
  Painting: ["Interior Painting", "Exterior Painting", "Cabinet Refinishing", "Drywall Repair", "Staining", "Free Estimates"],
  Solar: ["Panel Installation", "System Design", "Roof Assessment", "Battery Storage", "Maintenance & Repair", "Free Estimates"],
  "General Contractor": ["Remodeling", "Additions", "Framing", "Concrete Work", "Demolition", "Free Estimates"],
  Other: ["Repairs", "Installations", "Maintenance", "Inspections", "Emergency", "Free Estimates"],
};

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "DC", label: "District of Columbia" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
] as const;

export const DEFAULT_BANNER_MESSAGE = "Now booking spring projects — call today!";

export const TRADE_IMAGES: Record<string, string> = {
  "HVAC": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800",
  "Roofing": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
  "Plumbing": "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800",
  "Electrical": "/cover-electrician.png",
  "Landscaping": "/cover-landscaping.png",
  "Painting": "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800",
  "Solar": "/cover-solar.png",
  "General Contractor": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800",
  "default": "/cover-default.png",
};
