export const TRADES = [
  "HVAC",
  "Roofing",
  "Plumbing",
  "Electrical",
  "Landscaping",
  "Painting",
  "Solar",
  "General Contractor",
  "Other",
] as const;

export type Trade = (typeof TRADES)[number];

export const TRADE_SERVICES: Record<Trade, string[]> = {
  HVAC: ["AC Repair", "Furnace Install", "Duct Cleaning", "System Tune-Up", "Emergency HVAC", "Free Estimates"],
  Roofing: ["Roof Repair", "Roof Replacement", "Inspections", "Gutter Install", "Leak Repair", "Free Estimates"],
  Plumbing: ["Drain Cleaning", "Pipe Repair", "Water Heater", "Fixture Install", "Emergency Plumbing", "Free Estimates"],
  Electrical: ["Wiring & Rewiring", "Panel Upgrades", "Outlet Install", "Lighting", "Emergency Electrical", "Free Estimates"],
  Landscaping: ["Lawn Care", "Tree Trimming", "Hardscaping", "Irrigation", "Seasonal Cleanup", "Free Estimates"],
  Painting: ["Interior Painting", "Exterior Painting", "Cabinet Refinishing", "Drywall Repair", "Staining", "Free Estimates"],
  Solar: ["Panel Installation", "System Design", "Roof Assessment", "Battery Storage", "Maintenance & Repair", "Free Estimates"],
  "General Contractor": ["Remodeling", "Additions", "Framing", "Concrete Work", "Demolition", "Free Estimates"],
  Other: ["Repairs", "Installations", "Maintenance", "Inspections", "Emergency", "Free Estimates"],
};

export const SERVICE_DESCRIPTIONS: Record<string, string> = {
  "AC Repair": "Fast diagnosis and repair for all makes and models. Same-day appointments available.",
  "Furnace Install": "Professional furnace installation with expert sizing for your home.",
  "Duct Cleaning": "Complete duct cleaning to improve air quality and system efficiency.",
  "System Tune-Up": "Preventive maintenance to keep your system running at peak performance.",
  "Emergency HVAC": "24/7 emergency service because HVAC problems don't wait for business hours.",
  "Roof Repair": "Expert leak repair and damage restoration to protect your home.",
  "Roof Replacement": "Full tear-off and replacement with premium materials and workmanship.",
  "Inspections": "Thorough inspections to identify issues before they become expensive problems.",
  "Gutter Install": "Professional gutter installation to protect your foundation and landscaping.",
  "Leak Repair": "Fast, reliable leak detection and repair to prevent further damage.",
  "Drain Cleaning": "Professional drain clearing for stubborn clogs and slow drains.",
  "Pipe Repair": "Expert pipe repair and replacement for any plumbing issue.",
  "Water Heater": "Installation, repair, and replacement for all water heater types.",
  "Fixture Install": "Professional installation of faucets, toilets, sinks, and more.",
  "Emergency Plumbing": "24/7 emergency plumbing service for urgent repairs.",
  "Wiring & Rewiring": "Safe, code-compliant wiring for new construction and upgrades.",
  "Panel Upgrades": "Electrical panel upgrades to handle modern power demands safely.",
  "Outlet Install": "New outlet installation including GFCI and USB outlets.",
  "Lighting": "Indoor and outdoor lighting design, installation, and repair.",
  "Emergency Electrical": "24/7 emergency electrical service for dangerous situations.",
  "Lawn Care": "Professional mowing, edging, fertilization, and year-round maintenance.",
  "Tree Trimming": "Expert pruning and trimming to keep your trees healthy and beautiful.",
  "Hardscaping": "Patios, walkways, retaining walls, and outdoor living spaces.",
  "Irrigation": "Sprinkler system installation, repair, and seasonal maintenance.",
  "Seasonal Cleanup": "Spring and fall cleanup to keep your property looking its best.",
  "Interior Painting": "Professional interior painting with premium paints and clean edges.",
  "Exterior Painting": "Durable exterior painting that protects and beautifies your home.",
  "Cabinet Refinishing": "Transform your kitchen with professional cabinet refinishing.",
  "Drywall Repair": "Expert drywall repair, patching, and finishing.",
  "Staining": "Deck, fence, and wood staining for lasting beauty and protection.",
  "Panel Installation": "Professional solar panel installation with optimal positioning.",
  "System Design": "Custom solar system design sized for your energy needs.",
  "Roof Assessment": "Thorough roof evaluation for solar readiness and condition.",
  "Battery Storage": "Home battery systems for energy independence and backup power.",
  "Maintenance & Repair": "Ongoing solar system maintenance to maximize performance.",
  "Remodeling": "Full-service home remodeling from design to completion.",
  "Additions": "Room additions and home extensions built to code.",
  "Framing": "Professional structural framing for new construction and additions.",
  "Concrete Work": "Foundations, driveways, patios, and decorative concrete.",
  "Demolition": "Safe, efficient demolition and site preparation.",
  "Free Estimates": "Free, no-obligation estimates on all our services.",
};

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "DC", label: "District of Columbia" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
] as const;

export const DEFAULT_BANNER_MESSAGE = "Now booking spring projects — call today!";

export const TRADE_IMAGES: Record<string, string> = {
  "HVAC": "/cover-hvac.png",
  "Roofing": "/cover-roofing.png",
  "Plumbing": "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800",
  "Electrical": "/cover-electrician.png",
  "Landscaping": "/cover-landscaping.png",
  "Painting": "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800",
  "Solar": "/cover-solar.png",
  "General Contractor": "/cover-contractor.png",
  "default": "/cover-default.png",
};
