-- Remove the abandoned Google Business Profile integration and the plaintext
-- OAuth credentials it stored.
--
-- user_google_auth held access_token and refresh_token as bare `text`. The one
-- row is the owner's own Google account, granted with scope
-- `https://www.googleapis.com/auth/business.manage` -- full read/write on the
-- Google Business Profile, including posting and replying to reviews. The
-- access token expired 2026-04-02, but the refresh token does not expire on
-- its own and can still mint new access tokens until the grant is revoked.
--
-- Neither table has a single reference anywhere in the codebase; the
-- integration was never finished.
--
-- DO THIS FIRST -- revoking is not something the migration can do:
--
--   npx tsx scripts/revoke-google-oauth.ts            # report
--   npx tsx scripts/revoke-google-oauth.ts --revoke   # revoke
--
-- The usual route -- signing into the Google account and removing the app at
-- https://myaccount.google.com/permissions -- is not available: the account
-- (kthumm@rooftoppowerco.com) is no longer accessible.
--
-- Google's revocation endpoint accepts the token itself as the credential, so
-- possession is enough and no session or password is needed. The script reads
-- the refresh token straight from this table and revokes it, which also kills
-- every access token derived from it. It never prints the token.
--
-- Run the migration only once the script reports REVOKED (or reports that the
-- token was already invalid). Running it first destroys the only copy of the
-- token, which is also the only means of revoking the grant without the
-- account -- the grant would then stay live at Google with no way to reach it.
--
-- If the GBP integration is picked back up later, store tokens encrypted
-- (pgsodium / Supabase Vault) rather than as plaintext columns.

DROP TABLE IF EXISTS public.user_gbp_locations;
DROP TABLE IF EXISTS public.user_google_auth;
